{% set name = "climlab-sbm-convection" %}
{% set version = "0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/climlab/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 9ab1828fce993fc6a1de4a3d56ea6d4743fab6ac0837f46650921f1adbd7f4b9

build:
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<311 or win]  
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - meson-python                           # [build_platform != target_platform]
    - ninja                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('fortran') }}
  host:
    - meson-python
    - python
    - numpy
    - pip
  run:
    - python
    - numpy

test:
  requires:
    - pytest
  imports:
    - climlab_sbm_convection
  commands:
    - pytest -v --pyargs climlab_sbm_convection

about:
  home: https://github.com/climlab/climlab-sbm-convection
  summary: 'Standalone Python wrapper for the Simplified Betts-Miller moist convection model'
  description: |
    climlab-sbm-convection makes the Frierson Simplified Betts-Miller convection code callable from Python by wrapping using f2py. This is a lightweight wrapper that emulates the Fortran interface as closely as possible. The primary use case is to drive the convection process in climlab, but it can be used as a standalone driver if you are familiar with the Fortran interface.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/climlab/climlab-sbm-convection

extra:
  recipe-maintainers:
    - brian-rose
